export const sampleAiAuditEvents = [
  {
    userId: 'director-1',
    userRole: 'Director',
    interactionType: 'chat' as const,
    promptText: 'Summarize Nova AI',
    responseText: 'Nova AI robotics summary',
    retrievedChunkIds: ['emb-1'],
    retrievedCompanyIds: ['company-1'],
    modelId: 'anthropic.claude-3-sonnet',
    inputTokens: 100,
    outputTokens: 40,
    latencyMs: 850,
    piiRedactionsApplied: [],
  },
  {
    userId: 'intern-1',
    userRole: 'Intern',
    interactionType: 'retrieval' as const,
    promptText: 'Find robotics notes',
    responseText: null,
    retrievedChunkIds: ['emb-2'],
    retrievedCompanyIds: ['company-2'],
    modelId: 'amazon.titan-embed-text-v2',
    inputTokens: 20,
    outputTokens: 0,
    latencyMs: 120,
    piiRedactionsApplied: [{ field: 'email', action: 'masked' }],
  },
];
