sonar.projectKey=Prashanthiopsera_Deals-Tracker-CRM
sonar.organization=prashanthiopsera
sonar.projectName=Deals Tracker CRM
sonar.sources=backend/src
sonar.tests=backend/src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.typescript.tsconfigPath=backend/tsconfig.json
sonar.sourceEncoding=UTF-8
